root: /
admin_dir: kanri/
tpl: /html/user_data/packages/default/
admin_tpl: /html/user_data/packages/admin/
image_path: /html/upload/save_image/
root_dir: /Volumes/LaCie/MAMP/eccube-3
root_urlpath: null
template_code: default
admin_route: kanri
user_data_route: user_data
public_path: /html
public_path_realdir: /Volumes/LaCie/MAMP/eccube-3/html
image_save_realdir: /Volumes/LaCie/MAMP/eccube-3/html/upload/save_image
image_temp_realdir: /Volumes/LaCie/MAMP/eccube-3/html/upload/temp_image
user_data_realdir: /Volumes/LaCie/MAMP/eccube-3/html/user_data
block_default_realdir: /Volumes/LaCie/MAMP/eccube-3/src/Eccube/Resource/template/default/Block
block_realdir: /Volumes/LaCie/MAMP/eccube-3/app/template/default/Block
template_default_realdir: /Volumes/LaCie/MAMP/eccube-3/src/Eccube/Resource/template/default
template_default_html_realdir: /Volumes/LaCie/MAMP/eccube-3/html/template/default
template_admin_realdir: /Volumes/LaCie/MAMP/eccube-3/src/Eccube/Resource/template/admin
template_admin_html_realdir: /Volumes/LaCie/MAMP/eccube-3/html/template/admin
template_realdir: /Volumes/LaCie/MAMP/eccube-3/app/template/default
template_html_realdir: /Volumes/LaCie/MAMP/eccube-3/html/template/default
template_temp_realdir: /Volumes/LaCie/MAMP/eccube-3/app/cache/eccube/template
csv_temp_realdir: /Volumes/LaCie/MAMP/eccube-3/app/cache/eccube/csv
plugin_realdir: /Volumes/LaCie/MAMP/eccube-3/app/Plugin
plugin_temp_realdir: /Volumes/LaCie/MAMP/eccube-3/app/cache/plugin
plugin_html_realdir: /Volumes/LaCie/MAMP/eccube-3/html/plugin
admin_urlpath: /html/template/admin
front_urlpath: /html/template/default
image_save_urlpath: /html/upload/save_image
image_temp_urlpath: /html/upload/temp_image
user_data_urlpath: /html/user_data
plugin_urlpath: /html/plugin
