root: /
admin_dir: kanri/
tpl: /html/user_data/packages/default/
admin_tpl: /html/user_data/packages/admin/
image_path: /html/upload/save_image/
root_dir: /home/users/1/candle/web/cndl.jp/eshop
root_urlpath: null
template_code: default
admin_route: kanri
user_data_route: user_data
public_path: /html
public_path_realdir: /home/users/1/candle/web/cndl.jp/eshop/html
image_save_realdir: /home/users/1/candle/web/cndl.jp/eshop/html/upload/save_image
image_temp_realdir: /home/users/1/candle/web/cndl.jp/eshop/html/upload/temp_image
user_data_realdir: /home/users/1/candle/web/cndl.jp/eshop/html/user_data
block_default_realdir: /home/users/1/candle/web/cndl.jp/eshop/src/Eccube/Resource/template/default/Block
block_realdir: /home/users/1/candle/web/cndl.jp/eshop/app/template/default/Block
template_default_realdir: /home/users/1/candle/web/cndl.jp/eshop/src/Eccube/Resource/template/default
template_default_html_realdir: /home/users/1/candle/web/cndl.jp/eshop/html/template/default
template_admin_realdir: /home/users/1/candle/web/cndl.jp/eshop/src/Eccube/Resource/template/admin
template_admin_html_realdir: /home/users/1/candle/web/cndl.jp/eshop/html/template/admin
template_realdir: /home/users/1/candle/web/cndl.jp/eshop/app/template/default
template_html_realdir: /home/users/1/candle/web/cndl.jp/eshop/html/template/default
template_temp_realdir: /home/users/1/candle/web/cndl.jp/eshop/app/cache/eccube/template
csv_temp_realdir: /home/users/1/candle/web/cndl.jp/eshop/app/cache/eccube/csv
plugin_realdir: /home/users/1/candle/web/cndl.jp/eshop/app/Plugin
plugin_temp_realdir: /home/users/1/candle/web/cndl.jp/eshop/app/cache/plugin
plugin_html_realdir: /home/users/1/candle/web/cndl.jp/eshop/html/plugin
admin_urlpath: /html/template/admin
front_urlpath: /html/template/default
image_save_urlpath: /html/upload/save_image
image_temp_urlpath: /html/upload/temp_image
user_data_urlpath: /html/user_data
plugin_urlpath: /html/plugin
