<?php
/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Eccube\Common\Constant;

/**
 * CustomerFavoriteProductClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerFavoriteProductClassRepository extends EntityRepository
{
    /**
     * @param \Eccube\Entity\Customer $Customer
     * @param \Eccube\Entity\ProductClass  $ProductClass
     */
    public function addFavorite(\Eccube\Entity\Customer $Customer, \Eccube\Entity\ProductClass $ProductClass)
    {
        if ($this->isFavorite($Customer, $ProductClass)) {
            return;
        } else {
            $CustomerFavoriteProductClass = new \Eccube\Entity\CustomerFavoriteProductClass();
            $CustomerFavoriteProductClass->setCustomer($Customer);
            $CustomerFavoriteProductClass->setProductClass($ProductClass);
            $CustomerFavoriteProductClass->setDelFlg(Constant::DISABLED);

            $em = $this->getEntityManager();
            $em->persist($CustomerFavoriteProductClass);
            $em->flush();
        }
    }

    /**
     * @param  \Eccube\Entity\Customer $Customer
     * @param  \Eccube\Entity\ProductClass  $ProductClass
     * @return bool
     */
    public function isFavorite(\Eccube\Entity\Customer $Customer, \Eccube\Entity\ProductClass $ProductClass)
    {
        $qb = $this->createQueryBuilder('cf')
            ->select('COUNT(cf.ProductClass)')
            ->andWhere('cf.Customer = :Customer AND cf.ProductClass = :ProductClass')
            ->setParameters(array(
                'Customer' => $Customer,
                'ProductClass' => $ProductClass,
            ));
        $count = $qb
            ->getQuery()
            ->getSingleScalarResult();

        return $count > 0;
    }

    /**
     * @param  \Eccube\Entity\Customer $Customer
     * @param  \Eccube\Entity\ProductClass  $ProductClass
     * @return bool
     */
    public function deleteFavorite(\Eccube\Entity\Customer $Customer, \Eccube\Entity\ProductClass $ProductClass)
    {
        $qb = $this->createQueryBuilder('cf')
            ->andWhere('cf.Customer = :Customer AND cf.ProductClass = :ProductClass')
            ->setParameters(array(
                'Customer' => $Customer,
                'ProductClass' => $ProductClass,
            ));

        try {
            $CustomerFavoriteProductClass = $qb
                ->getQuery()
                ->getSingleResult();
        } catch (\Exception $e) {
            return false;
        }

        $em = $this->getEntityManager();
        $em->remove($CustomerFavoriteProductClass);
        $em->flush();

        return true;
    }

    /**
     * @param  \Eccube\Entity\Customer $Customer
     * @return QueryBuilder
     */
    public function getQueryBuilderByCustomer(\Eccube\Entity\Customer $Customer)
    {
        $qb = $this->createQueryBuilder('cfp')
            ->select('cfp, p')
            ->innerJoin('cfp.ProductClass', 'p')
            ->where('cfp.Customer = :Customer AND p.Status = 1')
            ->setParameter('Customer', $Customer);

        // Order By
        $qb->addOrderBy('cfp.create_date', 'DESC');

        return $qb;
    }
}
